# Start window and pane numbers at 1.
set -g base-index 1
setw -g pane-base-index 1

# Set terminal with proper colors.
set -s default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Fix vim mode switching delay.
# http://superuser.com/a/252717/65504
set -sg escape-time 0

# Increase scrollback buffer.
set -g history-limit 50000

# Use vim motion keys while in copy mode.
setw -g mode-keys vi

# Enable mouse support.
set -g mouse on

# Automatically renumber windows.
set -g renumber-windows on

# Allow arrow key to be used immediately after changing windows.
set -g repeat-time 0

# Dim inactive panes.
set -g pane-border-style bg=colour236
set -g pane-active-border-style bg=default
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'

# Update status bar every second.
set -g status-interval 1

# Show status bar at top.
set -g status-position top

# Set status bar colours.
set -g status-fg black
set -g status-bg white

# Customize status bar information.
set -g status-left ""
set -g status-right "#S #[default]"
set -g window-status-current-format " #I: #W "
set -g window-status-format " #I: #W "
set -g window-status-separator ""

# Highlight active status bar tab.
setw -g window-status-current-style fg=white,bg=black,bold

# Keep current path in new windows.
bind c new-window -c "#{pane_current_path}"

# Remap pane splitting keys.
bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Reload config.
bind r source-file ~/.tmux.conf \; display "Reloaded configuration."

# Swap order of windows using control-shift-left / control-shift-right.
# https://superuser.com/a/552493
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1
